#!/usr/bin/env python3
"""EP01 paper resplit v2. Does not touch the locked 29-shot table."""
from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parents[1]
ROOT = SCRIPTS.parent
sys.path.insert(0, str(SCRIPTS))

from director.pipeline import read_artifact
from director.shot_table import (
    needed_seconds,
    orientation_errors,
    pace_metrics,
    sanitize_shot_table,
    store_duration,
    validate_shot_table,
)
from director.video_profiles import get_profile

PROD = ROOT / "productions" / "010-gongpai"
OUT_JSON = PROD / ".pipeline" / "shot_list.ep01.resplit-v2.json"
OUT_MD = PROD / "03-storyboard" / "ep01-resplit-v2.md"
OUT_REVIEW = PROD / "03-storyboard" / "ep01-resplit-v2-review.md"

CAST = {"rin": "琳", "bopha": "波帕", "chanthy": "春安", "guard": "保安", "worker": "女工"}

# (from_old, dur, cov, scale, action, job, why, dlg_or_none, extra)
# extra: in_from, out_to, still_start, expression, the_shot, rewrite, mute, long,
#        camera_id, body_facing, camera_side, left, right, eyeline, hide, carrying,
#        costume, state_changes, visual_turn, hardest, evidence, key_sfx, move,
#        opening_hook, prompt_grid, note, emotion, angle, height, lens, beat
SPECS: list[tuple] = [
    # --- 开场 3 秒异常：裁员名单自己翻面 ---
    ("SH002", 1.0, "insert", "insert",
     "裁员名单纸边自己轻轻发颤",
     "开场异常第一拍：物件自己动",
     "开场模板 0–1s 主体轻微异常",
     None,
     {"opening_hook": True, "mute": "开场钩子",
      "still_start": "名单贴在玻璃上完全静止",
      "in_from": "开场只见门房玻璃上的名单人未入画",
      "out_to": "纸边还在微颤手还没伸进来",
      "expression": "无脸只物件",
      "the_shot": "纸边自己颤",
      "left": "名单纸边", "right": "玻璃反光", "eyeline": "名单最上那一行",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": False, "guard": False, "worker": False, "chanthy": False},
      "key_sfx": ["玻璃上纸边轻颤"],
      "prompt_grid": {
          "主体动作": "近景，裁员名单纸边自己轻轻发颤",
          "镜头运镜": "近景；镜头缓慢推进",
          "光线声音": "门房冷白一半灯；只保留玻璃轻颤",
          "停在": "名单最上那一行的纸边",
      },
      "visual_turn": True, "emotion": 6}),
    ("SH002", 1.0, "insert", "insert",
     "一只手伸向名单却突然停住",
     "开场异常第二拍：手伸向它却停住",
     "开场模板 1–2s 手停住",
     None,
     {"opening_hook": True, "mute": "开场钩子",
      "still_start": "手还在画外尚未伸入",
      "in_from": "纸边刚颤过手还没入画",
      "out_to": "手指停在玻璃前一寸没碰到纸",
      "expression": "无脸只手骤停",
      "the_shot": "手指停在玻璃前",
      "left": "伸来的手指", "right": "名单玻璃", "eyeline": "名单",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": True, "guard": False, "worker": False, "chanthy": False},
      "key_sfx": [],
      "prompt_grid": {
          "主体动作": "近景，一只手伸向名单却突然停住",
          "镜头运镜": "近景；镜头钉死不摇",
          "光线声音": "门房冷白一半灯；只保留布料摩擦骤停",
          "停在": "玻璃前一寸的指尖",
      },
      "emotion": 7}),
    ("SH002", 1.0, "insert", "insert",
     "最上那一行自己翻面停在她的名字",
     "开场异常第三拍：物件自己完成不该发生的变化",
     "开场模板 2–3s 自己翻面留下问题",
     None,
     {"opening_hook": True, "mute": "开场钩子",
      "still_start": "最上那一行还没翻面",
      "in_from": "手指仍停在玻璃前一寸",
      "out_to": "翻面停住最上是她的名字问题钉死",
      "expression": "无脸只物件",
      "the_shot": "名单最上怎么是她",
      "left": "翻开的名单行", "right": "玻璃反光", "eyeline": "最上那行名字",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": False, "guard": False, "worker": False, "chanthy": False},
      "evidence": ["门房玻璃上离职名单最上面是琳的名字"],
      "key_sfx": ["纸页自己翻面"],
      "prompt_grid": {
          "主体动作": "特写，名单最上那一行自己翻面",
          "镜头运镜": "特写；镜头钉死不摇",
          "光线声音": "门房冷白一半灯；只保留纸页翻面",
          "停在": "最上那行她的名字",
      },
      "visual_turn": True, "emotion": 8}),
    # --- 钩子之后才交代人在厂门 ---
    ("SH002", 2.2, "close", "close",
     "琳眼瞪大愣看玻璃上自己的名字",
     "钩子落地：脸上读出她看见了自己排头",
     "开场后第一张脸单独成镜",
     None,
     {"rewrite": "旧SH002 · 琳-独白「怎么又裁人，我名字怎么排头一个……」",
      "still_start": "她的眼还没瞪开",
      "in_from": "名单最上已是她的名字她的脸还没入近景",
      "out_to": "眼瞪着停住车还没入画",
      "expression": "琳眼瞪大愣住",
      "the_shot": "近脸瞪名单",
      "left": "琳脸", "right": "玻璃虚", "eyeline": "琳盯玻璃上最上面那一行",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": True, "guard": False, "worker": False, "chanthy": False},
      "emotion": 6}),
    ("SH001", 2.2, "single", "full",
     "琳咬牙把清洁车前轮卡过旧门槛",
     "钩子之后才交代她人在厂门车在身边",
     "地理后补：过门槛是一气动作",
     None,
     {"mute": "需补词",
      "still_start": "前轮还顶在门槛外侧尚未卡住",
      "in_from": "她刚瞪完名单车轮还在门槛外",
      "out_to": "车已过门槛门房在画左",
      "expression": "琳咬牙发急",
      "the_shot": "前轮卡门槛",
      "left": "琳与清洁车", "right": "铁门中偏右", "eyeline": "琳看旧门槛",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": True, "guard": False, "worker": False, "chanthy": False},
      "key_sfx": ["车轮卡旧门槛，响"],
      "visual_turn": True, "emotion": 5}),
    ("SH003", 2.2, "single", "medium",
     "琳转头横一眼始终不抬头的保安",
     "坐实她被无视",
     "视线转换单独一镜",
     None,
     {"mute": "需补词",
      "still_start": "她还没转头保安已坐在门房里",
      "in_from": "车已过门槛她尚未转头看保安",
      "out_to": "保安仍低头她已过门房",
      "expression": "琳横眼不服",
      "the_shot": "保安不抬头",
      "left": "门房里的保安、琳与清洁车", "right": "铁门与夹道纵深", "eyeline": "琳看不抬头的保安",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C01",
      "hide": {"rin": True, "guard": True, "worker": False, "chanthy": False},
      "emotion": 5}),
    ("SH004", 3.8, "single", "medium",
     "春安横着脸把旧钥匙举在手心里",
     "春安出场先压人钥匙还没扔",
     "扔之前钥匙必须先在她手里",
     None,
     {"rewrite": "旧SH004 · 春安-口白「琳，七线我春安管着，别在这儿晃，去把后面那间扫了。」",
      "still_start": "春安已在画右钥匙还没举平",
      "in_from": "她已过门房春安尚未入画出手",
      "out_to": "钥匙仍在春安手里尚未扔",
      "expression": "春安横脸讥",
      "the_shot": "钥匙还在她手里",
      "left": "琳与清洁车", "right": "春安举钥匙", "eyeline": "琳看春安手里的钥匙",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C01",
      "hide": {"rin": True, "chanthy": True, "guard": False, "worker": False},
      "carrying": {"chanthy": ["storeroom-key"]},
      "emotion": 6}),
    ("SH004", 4.2, "single", "medium",
     "春安把旧钥匙扔到琳脚边",
     "物件过手：钥匙离手落地",
     "那一颗：钥匙落地过程不拆",
     [{"character": "春安", "line": "后面那间，一年没人进。你去扫。"}],
     {"rewrite": "旧SH004 · 春安-口白「后面那间一年都没开过了，赶紧去。」",
      "still_start": "钥匙还在春安手里尚未出手",
      "in_from": "钥匙仍在春安手里",
      "out_to": "钥匙停在琳脚边地上",
      "expression": "春安横着甩手",
      "the_shot": "钥匙落地",
      "left": "琳与清洁车", "right": "春安扔完的手", "eyeline": "琳看将落的钥匙",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C01",
      "hide": {"rin": True, "chanthy": True, "guard": False, "worker": False},
      "carrying": {"chanthy": []},
      "state_changes": ["chanthy.carrying"],
      "hardest": True, "visual_turn": True,
      "key_sfx": ["钥匙落地"],
      "note": "扔必须入画：钥匙离手落地。琳在画左清洁车在身边；春安车间主管工装。春安还没走。胸前 T-0417 / TEMP。",
      "emotion": 7}),
    ("SH004", 2.5, "single", "full",
     "春安转身朝夹道深处走",
     "支开落在背影上",
     "物件落地后的走是第二件事",
     None,
     {"mute": "需补词",
      "still_start": "春安还面对琳尚未转身",
      "in_from": "钥匙已在地上春安尚未转身",
      "out_to": "春安背影朝画右深处",
      "expression": "春安背对她不屑",
      "the_shot": "她已经走了",
      "left": "琳清洁车地上的钥匙", "right": "春安转完身的背影",
      "eyeline": "琳看春安背影",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C01",
      "hide": {"rin": True, "chanthy": True, "guard": False, "worker": False},
      "emotion": 5}),
    ("SH005", 2.8, "single", "full",
     "琳急着对春安背影喊出半句",
     "琳想把七线问完",
     "对白换说话人单独一镜",
     [{"character": "琳", "line": "七线那边的油……"}],
     {"rewrite": "旧SH005 · 琳-口白「可七线地上的机油……」",
      "still_start": "她的嘴还没张开",
      "in_from": "春安已转身走钥匙仍在脚边",
      "out_to": "半句停在空气里春安不回头",
      "expression": "琳急得嘴扯开",
      "the_shot": "半句喊出去",
      "left": "琳与清洁车", "right": "春安背影", "eyeline": "琳看春安背影",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C01",
      "emotion": 6}),
    ("SH005", 2.8, "reverse", "medium",
     "春安头也不回讥一句把她顶回去",
     "春安一句顶回不回头",
     "换说话人",
     [{"character": "春安", "line": "油会自己干。"}],
     {"rewrite": "旧SH005 · 春安-口白「机油放着自己会干，少管闲事。」",
      "still_start": "春安背影未开口",
      "in_from": "琳的半句还在空气里",
      "out_to": "春安头也不回往画右深处走",
      "expression": "春安讥得过头",
      "the_shot": "油会自己干",
      "left": "琳与清洁车", "right": "春安背影", "eyeline": "春安不回头",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C01",
      "emotion": 6}),
    ("SH005", 2.0, "reaction", "close",
     "琳咬牙愣在近脸不再跟上",
     "对白后无词反应单独成立",
     "必须单独成立的反应",
     None,
     {"mute": "对白后反应",
      "still_start": "她的牙还没咬上",
      "in_from": "油会自己干刚落下",
      "out_to": "她近脸咬着牙没迈步",
      "expression": "琳咬牙横着",
      "the_shot": "近脸咬牙",
      "left": "琳脸", "right": "", "eyeline": "琳看春安背影方向",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": True, "chanthy": False, "guard": False, "worker": False},
      "emotion": 6}),
    ("SH006", 2.2, "single", "medium",
     "琳弯腰瞪着眼捡起脚边旧钥匙",
     "物件过手：钥匙离地入手",
     "捡和走拆开",
     None,
     {"rewrite": "旧SH006 · 琳-独白「催催催……去就去。」",
      "still_start": "她还没弯腰钥匙仍在地上",
      "in_from": "钥匙仍在脚边地上她尚未弯腰",
      "out_to": "钥匙已在手里",
      "expression": "琳瞪眼认命",
      "the_shot": "钥匙入手",
      "left": "琳与地上钥匙", "right": "清洁车", "eyeline": "琳看脚边钥匙",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C01",
      "carrying": {"rin": ["cleaning-cart", "storeroom-key"]},
      "state_changes": ["rin.carrying"],
      "visual_turn": True, "emotion": 5}),
    ("SH006", 2.5, "follow", "wide",
     "琳握着钥匙推车急走夹道",
     "结束在她独自走向夹道尽头",
     "捡完再走是第二件事",
     None,
     {"mute": "需补词",
      "still_start": "她还站在原地车尚未推动",
      "in_from": "钥匙已在手里车在身边",
      "out_to": "她拿着旧钥匙走向尽头",
      "expression": "琳急步咬牙",
      "the_shot": "独自走向尽头",
      "left": "琳与清洁车", "right": "夹道深处", "eyeline": "琳看夹道尽头",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C01",
      "move": "track",
      "move_reason": "不跟着走就看不见她独自走向夹道尽头",
      "visual_turn": True, "emotion": 5}),
    ("SH006", 2.0, "insert", "insert",
     "旧钥匙对准杂物间门锁",
     "走过的过程要接得上：钥匙对锁",
     "进门前钥匙必须入画",
     None,
     {"mute": "需补词",
      "still_start": "钥匙还没碰到锁孔",
      "in_from": "她已走到尽头钥匙还没插",
      "out_to": "钥匙插入门未开",
      "expression": "无脸只手急",
      "the_shot": "钥匙对锁",
      "left": "钥匙与锁", "right": "", "eyeline": "锁孔",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C01",
      "hide": {"rin": True, "chanthy": False, "guard": False, "worker": False},
      "emotion": 4}),
    # --- SC02 杂物间 ---
    ("SH007", 2.2, "single", "medium",
     "琳侧身挤进门框眼还瞪着",
     "进杂物间：人从门外到门内",
     "不能瞬移进扫",
     None,
     {"mute": "需补词",
      "still_start": "她人还在门槛外",
      "in_from": "门外钥匙刚转她人还在门槛外",
      "out_to": "她已在门内车与钥匙留在门外",
      "expression": "琳瞪眼挤进",
      "the_shot": "侧身进门",
      "left": "铁皮柜", "right": "门框与琳", "eyeline": "琳看门内暗处",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C10",
      "carrying": {"rin": []},
      "state_changes": ["rin.carrying"],
      "emotion": 5}),
    ("SH007", 2.2, "single", "medium",
     "琳抓起扫把横着脸对准窗台",
     "扫把入手单独成镜",
     "物件过手",
     None,
     {"mute": "需补词",
      "still_start": "扫把还在墙边未入手",
      "in_from": "她已进门扫把还在墙边",
      "out_to": "扫把在手里尚未开扫",
      "expression": "琳横脸不情愿",
      "the_shot": "扫把入手",
      "left": "琳与扫把", "right": "窗台", "eyeline": "琳看窗台",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C11",
      "carrying": {"rin": ["broom"]},
      "state_changes": ["rin.carrying"],
      "emotion": 4}),
    ("SH007", 2.5, "follow", "medium",
     "琳咬牙从窗台扫出一条灰",
     "给够扫地不要一进门就摸柜",
     "过程压到短切不是气氛长镜",
     None,
     {"mute": "需补词",
      "still_start": "灰还没被扫动",
      "in_from": "扫把已在手灰还没动",
      "out_to": "灰线扫到墙角柜前柜门未开",
      "expression": "琳咬牙干活",
      "the_shot": "灰线扫开",
      "left": "铁皮柜与琳", "right": "布头架", "eyeline": "窗台到墙角",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C11",
      "move": "track",
      "move_reason": "不跟就看不见她从窗台扫到墙角",
      "emotion": 4}),
    ("SH007", 2.0, "insert", "insert",
     "地面只留下她自己的脚印",
     "脚印只有她自己必须读清",
     "物件插入",
     None,
     {"mute": "需补词",
      "still_start": "地面灰还没露出脚印",
      "in_from": "灰线刚扫过地面尚未占画",
      "out_to": "脚印只有她自己",
      "expression": "无脸",
      "the_shot": "只有她的脚印",
      "left": "脚印", "right": "", "eyeline": "地面脚印",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True},
      "angle": "high",
      "emotion": 4}),
    ("SH008", 2.0, "insert", "insert",
     "她的手搭上虚掩柜门",
     "开柜动作起：手搭上门门尚未拉开",
     "从开柜拆出动作起",
     None,
     {"mute": "需补词",
      "still_start": "手还没碰到柜门",
      "in_from": "柜门仍虚掩手尚未搭上",
      "out_to": "手搭在虚掩柜门上柜内看不见工牌",
      "expression": "无脸只手",
      "the_shot": "手搭上门",
      "left": "铁皮柜门与手", "right": "", "eyeline": "柜门",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True},
      "emotion": 4}),
    ("SH008", 3.5, "single", "medium",
     "琳一气拉开虚掩铁皮柜",
     "信息在连续时间里：柜门一气打开从虚掩到灰工牌露出来",
     "拉开过程不中途切",
     None,
     {"long": "柜门一气打开",
      "mute": "需补词",
      "still_start": "柜门仍虚掩尚未拉开",
      "in_from": "手已搭上柜内仍暗",
      "out_to": "柜门已开灰工牌在柜内",
      "expression": "琳愣住拉开",
      "the_shot": "柜门一气打开",
      "left": "铁皮柜门与琳", "right": "柜内暗处", "eyeline": "柜内",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C10",
      "emotion": 6}),
    ("SH008", 2.0, "reaction", "close",
     "琳眼瞪大看见空柜里的灰工牌",
     "空柜入眼反应单独成立",
     "新信息点换了",
     None,
     {"rewrite": "旧SH008 · 琳-独白「柜子里空的？怎么就塞了块烂牌子……」",
      "still_start": "她的眼还没瞪到柜内",
      "in_from": "柜已开她刚看见",
      "out_to": "目光钉在灰工牌上手还没摸牌",
      "expression": "琳眼瞪大愣",
      "the_shot": "空柜只有牌",
      "left": "琳脸", "right": "柜内虚", "eyeline": "柜内灰工牌",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C12",
      "emotion": 6}),
    ("SH009", 2.2, "insert", "insert",
     "她的拇指抹掉工牌上的灰",
     "抹灰过程不拆",
     "读字之前先抹",
     None,
     {"mute": "需补词",
      "still_start": "拇指还没碰到灰皮",
      "in_from": "手碰到灰皮这是柜里那枚旧牌",
      "out_to": "灰掉了字面还没钉死",
      "expression": "无脸只手",
      "the_shot": "灰被抹掉",
      "left": "工牌与拇指", "right": "", "eyeline": "工牌字面",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "carrying": {"rin": ["bopha-badge", "broom"]},
      "state_changes": ["rin.carrying"],
      "hide": {"rin": True},
      "visual_turn": True, "emotion": 6}),
    ("SH009", 2.2, "insert", "insert",
     "姓名Bopha与职务常务副总停在特写",
     "证据入画必须读清",
     "抹和读拆开",
     None,
     {"rewrite": "旧SH009 · 琳-独白「波帕……常务副总？」",
      "still_start": "字面还没占满特写",
      "in_from": "灰已掉字面尚未钉死",
      "out_to": "字面已清她还没回头",
      "expression": "无脸只牌",
      "the_shot": "Bopha常务副总",
      "left": "工牌字面", "right": "", "eyeline": "工牌字面",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "evidence": ["工牌姓名 Bopha、职务常务副总"],
      "hide": {"rin": True},
      "visual_turn": True, "emotion": 7}),
    ("SH010", 2.2, "close", "close",
     "琳低头瞪着手里刚抹净的旧牌",
     "琳的脸还没看见身后",
     "纯视线",
     None,
     {"rewrite": "旧SH010 · 琳-独白「这哪是临时工带的牌子……」",
      "still_start": "她还没低头盯死",
      "in_from": "字面已清",
      "out_to": "仍低头看牌没有转身",
      "expression": "琳低头眼瞪大",
      "the_shot": "低头瞪牌",
      "left": "琳", "right": "柜门缝", "eyeline": "仍盯手中波帕旧牌",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C12",
      "emotion": 6}),
    ("SH011", 4.0, "single", "medium",
     "柜缝里灯管从白衫胸口透出",
     "信息在连续时间里：透身要给读清",
     "透胸禁止拆",
     None,
     {"long": "透胸可读",
      "mute": "透胸",
      "still_start": "身后柜缝还没有光",
      "in_from": "她还盯工牌身体朝向与上一镜相同",
      "out_to": "仍见胸口透光盖脚不见脸她仍未转身",
      "expression": "琳仍低头愣波帕不见脸",
      "the_shot": "灯管透胸",
      "left": "琳的左肩与颊侧", "right": "柜缝里胸口透光不见脸",
      "eyeline": "仍盯手中工牌没有去看身后",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C10",
      "hide": {"rin": True, "bopha": True},
      "evidence": ["灯管从胸口透过来，下摆盖脚，不见脸"],
      "visual_turn": True, "emotion": 8}),
    ("SH012", 2.0, "reaction", "close",
     "琳猛地回头眼瞪大",
     "怕单独成立尚未撞柜",
     "从撞柜前拆出回头",
     None,
     {"mute": "冲击",
      "still_start": "她还没回头",
      "in_from": "透胸刚看见她尚未回头",
      "out_to": "她已回头身体还没退撞",
      "expression": "琳怕得眼瞪大",
      "the_shot": "猛回头",
      "left": "琳脸", "right": "肩后暖金虚", "eyeline": "猛地看向身后偏右",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True, "bopha": False},
      "carrying": {"rin": ["bopha-badge", "broom"]},
      "emotion": 8}),
    ("SH012", 2.2, "reaction", "close",
     "琳怕得退撞画左柜门",
     "那一颗：怕从她脸上读出",
     "撞柜仍是全场最紧",
     None,
     {"mute": "冲击",
      "still_start": "她的背还没碰到柜门",
      "in_from": "她已回头尚未退撞",
      "out_to": "背撞上柜门扫把还在手里",
      "expression": "琳怕得脸拧起来",
      "the_shot": "退撞柜门",
      "left": "琳与铁皮柜", "right": "肩后暖金边缘", "eyeline": "看向身后偏右",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True, "bopha": False},
      "carrying": {"rin": ["bopha-badge", "broom"]},
      "hardest": True, "visual_turn": True, "emotion": 9}),
    ("SH012", 2.0, "insert", "insert",
     "扫把从她手里掉到脚边",
     "物件过手：扫把落地",
     "撞和掉拆开",
     None,
     {"mute": "冲击",
      "still_start": "扫把还在她手里",
      "in_from": "她已撞上扫把还在手里",
      "out_to": "扫把在脚边",
      "expression": "无脸",
      "the_shot": "扫把落地",
      "left": "扫把与脚边", "right": "", "eyeline": "地上扫把",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True, "bopha": False},
      "carrying": {"rin": ["bopha-badge"]},
      "state_changes": ["rin.carrying"],
      "key_sfx": ["扫把落地"],
      "emotion": 8}),
    ("SH013", 2.8, "single", "medium",
     "波帕侧脸逼近开口",
     "半身开口第一句不见正脸护照",
     "对白句单独一镜",
     [{"character": "波帕", "line": "你看得见我。"}],
     {"rewrite": "旧SH013 · 波帕-口白「我是波帕。你看得见我？」",
      "still_start": "波帕侧脸尚未开口",
      "in_from": "扫把已落",
      "out_to": "第一句落下仍半身",
      "expression": "波帕冷得过分逼近",
      "the_shot": "你看得见我",
      "left": "琳侧背与柜", "right": "波帕半身侧脸不见正脸",
      "eyeline": "波帕侧脸看琳",
      "body_facing": "侧脸", "camera_side": "front-right", "camera_id": "C10",
      "hide": {"rin": True, "bopha": True},
      "emotion": 7}),
    ("SH014", 2.8, "reverse", "medium",
     "琳结巴着嘴扯开问她是谁",
     "琳一句问无尖叫",
     "对白换说话人",
     [{"character": "琳", "line": "你、你谁——"}],
     {"rewrite": "旧SH014 · 琳-口白「你……你到底是人是……」",
      "still_start": "她的嘴还没扯开",
      "in_from": "第一句落",
      "out_to": "问句停在半截",
      "expression": "琳怕得嘴扯开",
      "the_shot": "你你谁",
      "left": "铁皮柜与琳", "right": "波帕偏右虚", "eyeline": "琳看身后偏右的波帕",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C11",
      "emotion": 8}),
    ("SH015", 4.0, "single", "medium",
     "波帕冷着气声自报只有她看得见",
     "可见规则落地仍半身",
     "从复合对白拆出第一信息",
     [{"character": "波帕", "line": "波帕。全厂只有你看得见。"}],
     {"rewrite": "旧SH015 · 波帕-口白「别嚷，全厂就你一个能看见我，跟别人说只会被当成中暑。」",
      "still_start": "波帕侧脸尚未说第二句",
      "in_from": "她问完",
      "out_to": "规则第一句落下仍半身",
      "expression": "波帕气声冷逼",
      "the_shot": "全厂只有你",
      "left": "琳侧", "right": "波帕半身", "eyeline": "波帕看琳",
      "body_facing": "侧脸", "camera_side": "front-right", "camera_id": "C10",
      "emotion": 7}),
    ("SH015", 2.5, "reverse", "medium",
     "波帕逼近说别对别人说",
     "第二句换了信息种类：保密",
     "同一人换信息就换镜",
     [{"character": "波帕", "line": "别对别人说。"}],
     {"rewrite": "旧SH015 · 波帕-口白「别嚷…跟别人说只会被当成中暑。」",
      "still_start": "这句话还没出口",
      "in_from": "全厂只有你看得见刚落",
      "out_to": "别对别人说落下",
      "expression": "波帕贴得更近",
      "the_shot": "别对别人说",
      "left": "琳", "right": "波帕半身", "eyeline": "波帕看琳",
      "body_facing": "侧脸", "camera_side": "front-right", "camera_id": "C10",
      "emotion": 8}),
    ("SH015", 4.2, "single", "medium",
     "波帕气声把中暑那句说完",
     "威胁落地仍半身脚不在画里",
     "长句单独给够秒",
     [{"character": "波帕", "line": "说了，他们只会当你中暑。"}],
     {"rewrite": "旧SH015 · 波帕-口白「跟别人说只会被当成中暑。」",
      "still_start": "中暑那句还没出口",
      "in_from": "别对别人说刚落",
      "out_to": "话说完仍半身脚不在画里",
      "expression": "波帕冷笑气声",
      "the_shot": "只会当你中暑",
      "left": "琳侧", "right": "波帕半身", "eyeline": "波帕看琳",
      "body_facing": "侧脸", "camera_side": "front-right", "camera_id": "C10",
      "emotion": 7}),
    ("SH015", 2.8, "single", "full",
     "波帕贴得更近把十五天说完",
     "十五条规则用一句人话落地",
     "rewrite 十五天单独一镜不塞进上一句",
     None,
     {"rewrite": "旧SH015 · 波帕-口白「听好，我们只有十五天时间。」",
      "still_start": "波帕还没把十五天说出口",
      "in_from": "中暑那句刚落",
      "out_to": "十五天落下仍盖脚",
      "expression": "波帕逼到过分",
      "the_shot": "只有十五天",
      "left": "琳与柜", "right": "波帕全身下摆", "eyeline": "波帕看琳",
      "body_facing": "侧脸", "camera_side": "front-right", "camera_id": "C10",
      "emotion": 8}),
    ("SH015", 2.0, "reaction", "close",
     "琳怕得咬住下唇说不出话",
     "对白后无词反应",
     "下一镜换题目门外喊",
     None,
     {"mute": "对白后反应",
      "still_start": "她的牙还没咬上唇",
      "in_from": "规则说完",
      "out_to": "琳停在近脸还没往门口看",
      "expression": "琳怕得咬唇",
      "the_shot": "咬唇说不出",
      "left": "琳脸", "right": "", "eyeline": "琳看波帕",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": True, "bopha": False},
      "emotion": 7}),
    ("SH016", 2.2, "master", "full",
     "琳猛地回头看中偏左的门",
     "门外喊琳牌还在手里",
     "门喊和塞袋拆开",
     None,
     {"rewrite": "旧SH016 · 女工-口白「琳！赶紧出来！」",
      "still_start": "她还没回头看门",
      "in_from": "旧牌仍在手里门还没人喊",
      "out_to": "喊名落下牌还在手里",
      "expression": "琳急得回头",
      "the_shot": "门外喊她",
      "left": "铁皮柜与琳", "right": "波帕全身下摆", "eyeline": "琳看中偏左的门",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C10",
      "key_sfx": ["门外喊她"],
      "emotion": 6}),
    ("SH016", 2.2, "single", "medium",
     "琳隔门急应一声",
     "隔门应声不抢门喊",
     "换说话人",
     None,
     {"rewrite": "旧SH016 · 琳-口白「来了！」",
      "still_start": "她的嘴还没应",
      "in_from": "门外喊名刚落牌还在手里",
      "out_to": "应声落下牌还在手里",
      "expression": "琳急得扯开嘴",
      "the_shot": "来了",
      "left": "琳与柜", "right": "门中偏左", "eyeline": "琳看门",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C11",
      "emotion": 6}),
    ("SH016", 2.2, "insert", "insert",
     "波帕下摆底下没有影子",
     "地上无影必须读清",
     "证据单独插入",
     None,
     {"mute": "需补词",
      "still_start": "地面还没露出无影",
      "in_from": "应声刚落地面尚未占画",
      "out_to": "下摆底下没有影子",
      "expression": "无脸",
      "the_shot": "地上没有影子",
      "left": "白衫下摆", "right": "空地", "eyeline": "地面",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C12",
      "hide": {"rin": False, "bopha": True},
      "evidence": ["波帕地上没有影子"],
      "visual_turn": True, "emotion": 7}),
    ("SH016", 2.2, "single", "medium",
     "琳把旧牌塞进围裙口袋",
     "物件入袋必须入画",
     "物件过手入袋",
     None,
     {"mute": "需补词",
      "still_start": "旧牌仍在手里尚未入袋",
      "in_from": "旧牌仍在手里喊名刚落",
      "out_to": "口袋略鼓旧牌已不在手里",
      "expression": "琳急着塞袋",
      "the_shot": "牌进口袋",
      "left": "琳与口袋", "right": "波帕下摆虚", "eyeline": "先看旧牌入袋",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C11",
      "carrying": {"rin": []},
      "state_changes": ["rin.carrying"],
      "visual_turn": True, "emotion": 6}),
    # --- SC03 走廊 → 七线 ---
    ("SH017", 2.2, "single", "medium",
     "琳从门里急步踏进走廊",
     "出门接走廊不能瞬移",
     "走过的过程要接得上",
     None,
     {"mute": "需补词",
      "still_start": "她的脚还在门内",
      "in_from": "口袋略鼓出门接走廊",
      "out_to": "她已在走廊轴侧波帕在右侧",
      "expression": "琳急步瞪眼",
      "the_shot": "踏进走廊",
      "left": "走廊近处与琳", "right": "波帕沿轴", "eyeline": "琳看走廊前方",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C30",
      "costume": {"bopha": "white-long-shirt-translucent"},
      "state_changes": ["bopha.costume"],
      "emotion": 6}),
    ("SH017", 2.5, "master", "full",
     "女工沿轴走近波帕身前",
     "交代走廊轴：走近尚未穿过",
     "不要等人走过来超过 3s",
     None,
     {"mute": "需补词",
      "still_start": "女工还在走廊深处尚未走近",
      "in_from": "琳已在轴侧女工还在深处",
      "out_to": "女工已到波帕身前尚未穿进白衬衫",
      "expression": "女工过分冷静琳眼瞪大",
      "the_shot": "女工走近尚未穿",
      "left": "走廊近处琳侧立", "right": "女工沿轴向画右走近波帕在轴上",
      "eyeline": "琳侧脸看轴上的波帕与走来的女工",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "worker": True, "chanthy": False},
      "emotion": 6}),
    ("SH018", 5.0, "single", "medium",
     "女工的肩穿进波帕白衬衫再穿出",
     "信息在连续时间里：穿过的进与出必须一镜内完成",
     "穿过禁止拆",
     None,
     {"long": "穿过进与出",
      "mute": "穿过",
      "still_start": "女工肩还没贴上白衬衫",
      "in_from": "女工已贴到波帕身前",
      "out_to": "肩刚出白衬衫女工头没偏",
      "expression": "女工头都不偏过分冷静",
      "the_shot": "肩从白衬衫里穿出",
      "left": "波帕白衬衫前中", "right": "女工肩沿轴向画右穿出",
      "eyeline": "女工看前方走廊头不偏",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C30",
      "hide": {"rin": False, "bopha": True, "worker": True, "chanthy": False},
      "evidence": ["女工肩从白衬衫里穿出，头都没偏"],
      "visual_turn": True, "emotion": 8}),
    ("SH019", 2.0, "reaction", "close",
     "琳眼瞪大嘴扯开却没出声",
     "穿过完成后给琳一眼",
     "反应压秒",
     None,
     {"mute": "冲击",
      "still_start": "她的嘴还没扯开",
      "in_from": "肩刚出白衬衫",
      "out_to": "目光仍钉在被穿过的位置嘴没出声",
      "expression": "琳怕得眼瞪大嘴扯开",
      "the_shot": "她看见了女工没有",
      "left": "琳脸", "right": "轴上刚被穿过的空位虚",
      "eyeline": "琳盯画右轴上刚被穿过的位置",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "bopha": False, "worker": False, "chanthy": False},
      "emotion": 8}),
    ("SH020", 2.2, "single", "medium",
     "琳回头死盯不回头的波帕",
     "确认别人当空气",
     "视线转换单独一镜",
     None,
     {"mute": "需补词",
      "still_start": "她还没回头看波帕",
      "in_from": "她的眼已在动尚未回头看波帕",
      "out_to": "只有她回头波帕不转",
      "expression": "琳怕急回头波帕冷得过分",
      "the_shot": "只有她回头",
      "left": "琳", "right": "波帕沿轴", "eyeline": "琳回头看波帕",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "worker": False, "chanthy": False},
      "emotion": 7}),
    ("SH020", 2.0, "follow", "full",
     "女工头也不回走出画",
     "穿过了还在走落幅读清",
     "走廊结束在脚步不停",
     None,
     {"mute": "需补词",
      "still_start": "女工还在画里尚未出画",
      "in_from": "琳已回头",
      "out_to": "女工出画脚步不停",
      "expression": "女工过分冷静",
      "the_shot": "女工出画",
      "left": "走廊近处", "right": "女工沿轴出画", "eyeline": "女工看前方",
      "body_facing": "侧脸", "camera_side": "front-left", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "worker": True, "chanthy": False},
      "emotion": 5}),
    ("SH021", 2.0, "insert", "insert",
     "琳的胶鞋急踩走廊地面",
     "走廊到七线要接得上",
     "短切脚步不能瞬移",
     None,
     {"mute": "需补词",
      "still_start": "胶鞋还没迈出这一步",
      "in_from": "女工出画她的脚还没迈向门口",
      "out_to": "脚步朝门口去",
      "expression": "无脸只脚急",
      "the_shot": "急踩地面",
      "left": "胶鞋", "right": "地面", "eyeline": "地面",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": False, "worker": False, "chanthy": False},
      "angle": "high",
      "emotion": 5}),
    ("SH021", 2.0, "insert", "insert",
     "七线门框从肩边擦过",
     "走过门口",
     "短切门框",
     None,
     {"mute": "需补词",
      "still_start": "门框还在肩前",
      "in_from": "脚步朝门口门框尚未擦过",
      "out_to": "门框过去车间灯管在前",
      "expression": "无脸只肩",
      "the_shot": "门框擦过",
      "left": "门框", "right": "肩", "eyeline": "门",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": False, "worker": False, "chanthy": False},
      "emotion": 5}),
    ("SH021", 2.5, "master", "full",
     "琳愣在半圆围人中间的清洁车旁",
     "地理 master：半圆围观是墙车在中间",
     "建立压到短切",
     None,
     {"mute": "需补词",
      "still_start": "围人还没占满画",
      "in_from": "她刚过门框围人还没占满画",
      "out_to": "围人可读拉链还没特写",
      "expression": "琳愣怕围观横着看她",
      "the_shot": "半圆围人车在中间",
      "left": "琳与清洁车", "right": "春安女工们半圆靠门十四号机前中偏右",
      "eyeline": "围观看车与琳",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": True},
      "carrying": {"rin": ["cleaning-cart"]},
      "state_changes": ["rin.carrying"],
      "emotion": 7}),
    ("SH021", 2.0, "insert", "insert",
     "清洁车底层拉链敞着",
     "车拉链未拉给观众先看见",
     "物件插入",
     None,
     {"mute": "需补词",
      "still_start": "拉链还没占满特写",
      "in_from": "车在中间拉链尚未占画",
      "out_to": "拉链未拉可读",
      "expression": "无脸",
      "the_shot": "拉链未拉",
      "left": "清洁车拉链", "right": "", "eyeline": "拉链",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "bopha": False, "chanthy": False, "worker": False},
      "visual_turn": True, "emotion": 6}),
    ("SH022", 2.2, "insert", "insert",
     "春安横着把藏青布从车底拖出",
     "赃物出手：布离开车底",
     "拖和甩拆开",
     None,
     {"mute": "需补词",
      "still_start": "布还在底层没被拖出",
      "in_from": "手伸向底层布还没出来",
      "out_to": "布已离车底尚未甩开",
      "expression": "春安横手",
      "the_shot": "布被拖出",
      "left": "清洁车底层", "right": "藏青布", "eyeline": "车底层",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "chanthy": True, "bopha": False, "worker": False},
      "angle": "high",
      "emotion": 7}),
    ("SH022", 2.2, "insert", "insert",
     "藏青布甩在地上吊牌朝上",
     "赃物落地吊牌必须读清",
     "甩是第二件事",
     None,
     {"mute": "需补词",
      "still_start": "布还没甩向地面",
      "in_from": "布已离车底尚未甩开",
      "out_to": "布落地铺开吊牌朝上可见",
      "expression": "无脸只布",
      "the_shot": "吊牌还在",
      "left": "清洁车底层", "right": "藏青布与吊牌", "eyeline": "吊牌",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "chanthy": True, "bopha": False, "worker": False},
      "evidence": ["藏青布吊牌还在"],
      "visual_turn": True, "angle": "high",
      "emotion": 8}),
    ("SH023", 4.0, "otc", "otc",
     "春安指着地上的布横着指控",
     "指控句一：藏青在车底",
     "从复合指控拆出第一信息",
     [{"character": "春安", "line": "节前丢的那批，在她车里。"}],
     {"rewrite": "旧SH023 · 春安-口白「节前丢的那批藏青布，吊牌都没拆，全在这车底下塞着！」",
      "still_start": "春安的手还没指向布",
      "in_from": "布已在地上",
      "out_to": "句一落下春安仍在越肩",
      "expression": "春安横着指控",
      "the_shot": "在她车里",
      "left": "琳肩前景", "right": "春安中景", "eyeline": "春安看琳与地上的布",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "chanthy": True, "bopha": False, "worker": False},
      "emotion": 8}),
    ("SH023", 2.0, "reaction", "medium",
     "围观女工齐齐横眼看地上的布",
     "围观反应单独成立",
     "必须单独成立的反应",
     None,
     {"mute": "对白后反应",
      "still_start": "围观的眼还没齐齐转过去",
      "in_from": "句一刚落",
      "out_to": "围观目光钉在布上",
      "expression": "围观齐齐横眼",
      "the_shot": "围观钉在布上",
      "left": "围观的脸", "right": "地上的布", "eyeline": "看地上的布",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "chanthy": False, "bopha": False, "worker": True},
      "note": "围观看地上的布。春安不到特写不入近景。波帕本镜不抢画。",
      "emotion": 7}),
    ("SH023", 3.8, "otc", "otc",
     "春安讥着说临时工手脚不干净",
     "指控句二：临时工",
     "同一人换信息就换镜",
     [{"character": "春安", "line": "临时工，手脚比机器还快。"}],
     {"rewrite": "旧SH023 · 春安-口白「临时工手脚不干净，今天签了字赶紧滚！」",
      "still_start": "这句还没出口",
      "in_from": "围观一眼刚切走",
      "out_to": "临时工那句落下",
      "expression": "春安讥得过头",
      "the_shot": "临时工不干净",
      "left": "琳肩前景", "right": "春安中景", "eyeline": "春安看琳",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "chanthy": True, "bopha": False, "worker": False},
      "emotion": 8}),
    ("SH023", 3.2, "reverse", "medium",
     "春安横着勒令今天签字今天走",
     "指控句三：签字滚蛋",
     "第三句换信息再拆",
     [{"character": "春安", "line": "今天签字，今天走。"}],
     {"rewrite": "旧SH023 · 春安-口白「今天签了字赶紧滚！」",
      "still_start": "签字那句还没出口",
      "in_from": "临时工那句刚落",
      "out_to": "指控句说完",
      "expression": "春安横着勒令",
      "the_shot": "今天签字今天走",
      "left": "琳与清洁车", "right": "春安中景", "eyeline": "春安看琳",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "chanthy": True, "bopha": False, "worker": False},
      "emotion": 8}),
    ("SH024", 2.8, "reaction", "close",
     "琳急得嘴扯开要辩解",
     "琳想辩解",
     "从开口拆出",
     [{"character": "琳", "line": "车……车一直停在——"}],
     {"rewrite": "旧SH024 · 琳-口白「车子一直停在七线外边，底下敞着……我根本没……」",
      "still_start": "她的嘴还没扯开",
      "in_from": "指控刚落",
      "out_to": "话只说出半截",
      "expression": "琳急怕嘴扯开",
      "the_shot": "车一直停在",
      "left": "琳脸", "right": "", "eyeline": "眼白先看画右春安方向",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "chanthy": False, "bopha": False, "worker": False},
      "carrying": {"rin": []},
      "state_changes": ["rin.carrying"],
      "emotion": 8}),
    ("SH024", 2.0, "close", "close",
     "琳话散了眼从春安落到车的方向",
     "辩解失败视线转换",
     "话散了是第二件事",
     None,
     {"mute": "对白后反应",
      "still_start": "眼神还钉在春安方向",
      "in_from": "半句还在嘴边",
      "out_to": "眼神停在车的方向",
      "expression": "琳眼散了怕",
      "the_shot": "话散了看车",
      "left": "琳脸", "right": "车的方向虚", "eyeline": "车的方向",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "chanthy": False, "bopha": False, "worker": False},
      "note": "只琳近脸车不入画只靠眼神落到身侧车的方向。口袋略鼓干装。",
      "emotion": 7}),
    ("SH025", 2.0, "insert", "insert",
     "摊开的辞退单钉在机台面上",
     "先给纸",
     "从摊书拧帽拆出纸",
     None,
     {"rewrite": "旧SH025 · 琳-独白「辞退单……」",
      "still_start": "台面还没被纸占满",
      "in_from": "台面还没有摊开的书占画",
      "out_to": "辞退单已摊开笔帽未拧",
      "expression": "无脸",
      "the_shot": "辞退单摊开",
      "left": "摊开的离职书", "right": "", "eyeline": "纸面",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "chanthy": False, "bopha": False, "worker": False},
      "angle": "high",
      "visual_turn": True, "emotion": 7}),
    ("SH025", 2.0, "insert", "insert",
     "一只手把笔帽拧开",
     "再给拧开的笔帽",
     "物件过手纸和帽都能读",
     None,
     {"mute": "需补词",
      "still_start": "笔帽还没被拧",
      "in_from": "纸已摊开笔帽未拧",
      "out_to": "笔帽已开笔尖不落纸",
      "expression": "无脸只手横",
      "the_shot": "笔帽拧开",
      "left": "摊开的纸", "right": "笔帽", "eyeline": "笔帽",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "chanthy": False, "bopha": False, "worker": False},
      "key_sfx": ["笔帽拧开"],
      "angle": "high",
      "visual_turn": True, "emotion": 7}),
    ("SH026", 2.5, "single", "medium",
     "全场横着等她她手在桌边僵住",
     "对峙里权力没切点压成短拳",
     "对峙留白不和别认叠",
     None,
     {"mute": "需补词",
      "still_start": "她的手还没僵在桌边",
      "in_from": "笔帽已开手还没伸",
      "out_to": "手仍在桌边不动",
      "expression": "琳怕得手僵春安讥围观横",
      "the_shot": "手在桌边不动",
      "left": "琳清洁车波帕贴右肩", "right": "春安桌上纸笔围观虚",
      "eyeline": "春安看琳的手",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": True},
      "carrying": {"rin": ["cleaning-cart"]},
      "state_changes": ["rin.carrying"],
      "emotion": 8}),
    ("SH026", 2.8, "reverse", "medium",
     "春安横着逼她签字",
     "春安一句签",
     "换说话人",
     [{"character": "春安", "line": "签。"}],
     {"rewrite": "旧SH026 · 春安-口白「愣着干什么，按手印签字！」",
      "still_start": "春安还没吐出这个字",
      "in_from": "全场还在等",
      "out_to": "签字落下",
      "expression": "春安横到过分",
      "the_shot": "签",
      "left": "琳与清洁车", "right": "春安中景", "eyeline": "春安看琳",
      "body_facing": "四分之三", "camera_side": "front-right", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": True},
      "note": "春安中景不到特写；琳手不伸向笔；围观是墙。波帕贴右肩但不抢这句。",
      "emotion": 8}),
    ("SH026", 2.8, "single", "medium",
     "波帕贴在她右肩气声说别认",
     "波帕只对琳说别认",
     "换说话人不和等签穿过叠",
     [{"character": "波帕", "line": "别认。"}],
     {"rewrite": "旧SH026 · 波帕-口白「别认。」",
      "still_start": "波帕还没贴到右肩开口",
      "in_from": "签字刚落手仍不动",
      "out_to": "别认落下手仍不动",
      "expression": "波帕气声冷逼琳眼瞪大",
      "the_shot": "别认",
      "left": "琳波帕贴其右肩", "right": "春安虚", "eyeline": "波帕看琳",
      "body_facing": "四分之三", "camera_side": "front-left", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": False},
      "note": "波帕贴琳右肩暖金只在衣缘下摆盖脚无影不越轴；琳手不伸向笔。",
      "emotion": 9}),
    ("SH026", 3.5, "single", "full",
     "围观从波帕身上穿过去看热闹",
     "信息在连续时间里：有人从波帕身上穿过看热闹",
     "三件事拆开穿过单独一镜",
     None,
     {"long": "有人穿过看热闹",
      "mute": "穿过",
      "still_start": "围观还没贴上波帕的身体",
      "in_from": "别认刚落",
      "out_to": "有人从波帕身上穿过去",
      "expression": "围观过分冷静穿过琳怕",
      "the_shot": "别人穿过看热闹",
      "left": "琳波帕贴右肩", "right": "穿过的围观", "eyeline": "围观看热闹不看波帕",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": True},
      "emotion": 8}),
    ("SH027", 2.0, "reaction", "close",
     "琳抬眼咬牙",
     "琳抬眼视线不落笔尖",
     "反应压到短拳",
     None,
     {"mute": "冲击",
      "still_start": "她的眼还没抬",
      "in_from": "别认刚落有人刚穿过",
      "out_to": "琳抬眼结束仍近景",
      "expression": "琳抬眼咬牙",
      "the_shot": "抬眼",
      "left": "琳脸", "right": "", "eyeline": "琳抬眼不看笔尖",
      "body_facing": "朝镜头", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": False, "chanthy": False, "worker": False},
      "carrying": {"rin": []},
      "state_changes": ["rin.carrying"],
      "emotion": 9}),
    ("SH028", 4.5, "insert", "insert",
     "笔尖悬在纸上没有手伸过来",
     "信息在连续时间里：笔尖悬停是那一颗",
     "笔尖不拆",
     None,
     {"long": "笔尖悬停",
      "mute": "笔尖",
      "still_start": "笔尖已经停在纸上但镜头还没钉死",
      "in_from": "琳已抬眼",
      "out_to": "停在没人拿的笔上",
      "expression": "无脸只笔",
      "the_shot": "笔还在桌上她没签",
      "left": "摊开的纸", "right": "笔留在桌上", "eyeline": "笔尖",
      "body_facing": "无人", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": False, "bopha": False, "chanthy": False, "worker": False},
      "evidence": ["笔还在桌上，她没签"],
      "hardest": True, "visual_turn": True,
      "angle": "high",
      "emotion": 9}),
    ("SH029", 2.5, "master", "medium",
     "琳站着咬牙没签",
     "峰值后回中景：这一天还没死",
     "回中景钩子",
     None,
     {"rewrite": "旧SH029 · 琳-独白「不是我拿的，休想让我认。」",
      "still_start": "她还没把没签的站姿钉住",
      "in_from": "笔没人拿",
      "out_to": "本集停在没签",
      "expression": "琳咬牙春安横波帕冷贴右肩",
      "the_shot": "她没签",
      "left": "琳车波帕贴右肩", "right": "春安与围观桌上纸笔仍在",
      "eyeline": "琳不看春安正脸看空处",
      "body_facing": "四分之三", "camera_side": "front", "camera_id": "C30",
      "hide": {"rin": True, "bopha": True, "chanthy": True, "worker": True},
      "carrying": {"rin": ["cleaning-cart"]},
      "state_changes": ["rin.carrying"],
      "emotion": 8}),
]


def inherit(parent: dict, **over) -> dict:
    shot = copy.deepcopy(parent)
    shot.pop("shot_id", None)
    if "dialogue_ref" not in over:
        shot["dialogue_ref"] = []
        shot["dialogue_delivery"] = "none"
    if "state_changes" not in over:
        shot["state_changes"] = []
    shot["internal_cuts"] = []
    shot["hardest"] = False
    shot["visual_turn"] = False
    shot.update(over)
    shot["action_ref"] = shot.get("one_action")
    return shot


def set_in_frame(shot: dict, **flags) -> None:
    chars = ((shot.get("state") or {}).get("characters") or {})
    for cid, flag in flags.items():
        item = chars.get(cid)
        if isinstance(item, dict):
            item["in_frame"] = flag


def set_carrying(shot: dict, carrying: dict[str, list]) -> None:
    chars = ((shot.get("state") or {}).get("characters") or {})
    for cid, items in carrying.items():
        item = chars.get(cid)
        if isinstance(item, dict):
            item["carrying"] = list(items)


def set_costume(shot: dict, costume: dict[str, str]) -> None:
    chars = ((shot.get("state") or {}).get("characters") or {})
    for cid, token in costume.items():
        item = chars.get(cid)
        if isinstance(item, dict):
            item["costume"] = token


def set_note(shot: dict, note: str) -> None:
    state = shot.get("state")
    if isinstance(state, dict):
        state["note"] = note


def in_frame_names(shot: dict) -> list[str]:
    chars = ((shot.get("state") or {}).get("characters") or {})
    return [CAST.get(cid, cid) for cid, item in chars.items() if isinstance(item, dict) and item.get("in_frame")]


def main() -> None:
    official = json.loads((PROD / ".pipeline" / "shot_list.json").read_text(encoding="utf-8"))
    by_old = {s["shot_id"]: s for s in official["shots"]}
    shots: list[dict] = []
    cards: list[dict] = []

    for index, spec in enumerate(SPECS, start=1):
        old_id, dur, cov, scale, action, job, why, dlg, extra = spec
        extra = dict(extra)
        new_id = f"SH{index:03d}"
        parent = by_old[old_id]
        hide = extra.pop("hide", None)
        carrying = extra.pop("carrying", None)
        costume = extra.pop("costume", None)
        note = extra.pop("note", None)
        rewrite = extra.pop("rewrite", None)
        mute = extra.pop("mute", None)
        long_why = extra.pop("long", None)
        move = extra.pop("move", None)
        move_reason = extra.pop("move_reason", None)
        emotion = extra.pop("emotion", None)
        still_start = extra.pop("still_start", "")
        expression = extra.pop("expression", "")
        the_shot = extra.pop("the_shot", "")
        prompt_grid = extra.pop("prompt_grid", None)
        opening_hook = extra.pop("opening_hook", False)

        over = {
            "shot_id": new_id,
            "duration_sec": dur,
            "coverage_type": cov,
            "scale": scale,
            "one_action": action,
            "shot_job": job,
            "from_old": old_id,
            "split_reason": why,
            "still_start": still_start,
            "expression": expression,
            "the_shot": the_shot,
            "internal_cuts": [],
        }
        if dlg:
            over["dialogue_ref"] = dlg
            over["dialogue_delivery"] = "post"
        if move:
            over["move_type"] = move
            over["move_needed"] = "move"
            over["move_reason"] = move_reason or ""
        else:
            over["move_type"] = "static"
            over["move_needed"] = "static"
            over["move_reason"] = ""
        if emotion is not None:
            over["emotion_level"] = emotion
        if opening_hook:
            over["opening_hook"] = True
        if prompt_grid:
            over["prompt_grid"] = prompt_grid
        if long_why:
            over["long_take_reason"] = f"信息在连续时间里：{long_why}"
        if rewrite:
            goes = rewrite
        elif mute == "需补词":
            goes = "需补词"
        elif mute:
            goes = f"无词（{mute}）"
        else:
            goes = "需补词"
        over["dialogue_goes_to"] = goes
        extra.pop("dialogue_goes_to", None)
        over.update(extra)
        shot = inherit(parent, **over)
        if hide:
            set_in_frame(shot, **hide)
        if carrying:
            set_carrying(shot, carrying)
        if costume:
            set_costume(shot, costume)
        if note:
            set_note(shot, note)
        names = in_frame_names(shot)
        shot["characters"] = names
        shot["continuity"] = {
            "binding": f"接：{shot.get('in_from')}；交：{shot.get('out_to')}",
            "still_start": still_start,
        }
        need = needed_seconds(shot)
        if not shot.get("opening_hook") and float(shot.get("duration_sec") or 0) + 0.05 < need:
            shot["duration_sec"] = store_duration(need)
        shots.append(shot)
        cards.append(
            {
                "id": new_id,
                "from_old": old_id,
                "scene": shot["scene_id"],
                "location": shot.get("location_id"),
                "duration": shot["duration_sec"],
                "coverage": shot["coverage_type"],
                "scale": shot["scale"],
                "camera": shot.get("camera_id") or "",
                "one_action": action,
                "expression": expression,
                "the_shot": the_shot,
                "still_start": still_start,
                "who": "、".join(f"{d['character']}：{d['line']}" for d in (shot.get("dialogue_ref") or [])) or "—",
                "why": why,
                "in_from": shot.get("in_from"),
                "out_to": shot.get("out_to"),
                "dialogue_goes_to": goes,
                "names": "、".join(names) or "—",
                "mute": mute or "",
                "long": long_why or "",
                "prompt_grid": prompt_grid,
                "opening_hook": opening_hook,
            }
        )

    payload = copy.deepcopy(official)
    payload["shots"] = shots
    payload["status"] = "candidate"
    payload["locked_picture"] = False
    payload["pace_profile"] = "tight_2_4"
    payload["pace"] = "2-4"
    payload["resplit_of"] = "shot_list.json"
    payload["resplit_version"] = "v2"
    payload["origin"] = "shot-split-v2-2026-09-14"
    payload["picture_table"] = "shot_list.json"
    payload["agent"] = "design"
    payload["notes"] = (
        "EP01 纸面重拆 v2。活表 .pipeline/shot_list.json 仍是 29 镜锁画。"
        "开场 3 秒名单自己翻面。对白映射旧镜号与 ep01-dialogue-rewrite.md。未进新表、不回炉。"
    )
    payload["opening_anomaly"] = {
        "object": "门房玻璃上的裁员名单",
        "question": "名单最上怎么是她？",
        "shots": ["SH001", "SH002", "SH003"],
        "seconds": 3,
    }
    payload["scene_plan"] = [
        {"scene_id": "EP01_SC01", "target_shots": 16, "target_sec": 36, "beats": official["scene_plan"][0]["beats"]},
        {"scene_id": "EP01_SC02", "target_shots": 25, "target_sec": 62, "beats": official["scene_plan"][1]["beats"]},
        {"scene_id": "EP01_SC03", "target_shots": 26, "target_sec": 70, "beats": official["scene_plan"][2]["beats"]},
    ]
    writer = read_artifact(PROD, "writer.json")
    payload = sanitize_shot_table(payload, writer=writer)
    for card, shot in zip(cards, payload["shots"]):
        card["duration"] = shot["duration_sec"]
    payload["status"] = "candidate"
    payload["locked_picture"] = False
    payload["pace_profile"] = "tight_2_4"
    payload["pace"] = "2-4"
    payload["resplit_of"] = "shot_list.json"
    payload["resplit_version"] = "v2"
    payload["picture_table"] = "shot_list.json"
    sets = json.loads((PROD / "03-storyboard" / "sets.json").read_text(encoding="utf-8"))
    look = (PROD / "02-assets" / "LOOK.md").read_text(encoding="utf-8")
    errors, warnings = validate_shot_table(
        payload,
        writer=writer,
        sets=sets,
        profile=get_profile(payload.get("target_model") or "seedance_2_0"),
        look_text=look,
        prod=PROD,
    )
    face_errors = orientation_errors(payload["shots"])
    metrics = pace_metrics(payload["shots"])
    long_takes = [
        s for s in payload["shots"]
        if float(s.get("duration_sec") or 0) > 4.0 and s.get("long_take_reason")
    ]
    over4 = [s for s in payload["shots"] if float(s.get("duration_sec") or 0) > 4.0]
    dlg_shots = [s for s in payload["shots"] if s.get("dialogue_ref")]
    rewrite_shots = [c for c in cards if str(c["dialogue_goes_to"]).startswith("旧")]
    mute_shots = [c for c in cards if str(c["dialogue_goes_to"]).startswith("无词")]
    need_line = [c for c in cards if c["dialogue_goes_to"] == "需补词"]
    payload["warnings"] = warnings
    payload["validation"] = {
        "errors": errors,
        "orientation_errors": face_errors,
        "warning_count": len(warnings),
    }
    payload["metrics"] = {
        **metrics,
        "long_takes": len(long_takes),
        "over_4s": len(over4),
        "dialogue_ref_shots": len(dlg_shots),
        "rewrite_mapped": len(rewrite_shots),
        "mute_allowed": len(mute_shots),
        "need_line": len(need_line),
    }
    payload["total_sec"] = store_duration(metrics["total_sec"])
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    _write_cards_md(cards, metrics, errors, warnings, long_takes, dlg_shots, mute_shots, need_line)
    _write_review(cards, metrics, errors, warnings, long_takes, dlg_shots, rewrite_shots, mute_shots, need_line)
    print(json.dumps({
        "json": str(OUT_JSON),
        "md": str(OUT_MD),
        "review": str(OUT_REVIEW),
        "metrics": payload["metrics"],
        "errors": errors,
        "orientation": face_errors,
        "warnings": warnings[:30],
    }, ensure_ascii=False, indent=2))
    if errors or face_errors:
        sys.exit(1)


def _write_cards_md(cards, metrics, errors, warnings, long_takes, dlg_shots, mute_shots, need_line) -> None:
    lines = [
        "# EP01 纸面重拆 v2",
        "",
        "状态：**candidate**。活表 `.pipeline/shot_list.json`（29 镜）仍是锁画表。",
        "本表不覆盖官方 `04-frames/*.jpg`、`05-shots/SH*.mp4`、SRT。",
        "对白工作轨 / SRT 仍按 **旧镜号**。`dialogue_goes_to` 指向旧 29 镜与 `ep01-dialogue-rewrite.md`。",
        "",
        f"- 候选：`.pipeline/shot_list.ep01.resplit-v2.json`",
        f"- 镜数：**{metrics['shots']}** · 纸面秒：**{metrics['total_sec']}** · ASL **{metrics['asl']}s** · SPM **{metrics['spm']}**",
        f"- 节奏档：`pace_profile=tight_2_4` · 默认 2–4s · 开场 3×1s",
        f"- 长镜头（>4s 且写了连续时间理由）：**{len(long_takes)}**",
        f"- 有 writer 对白：**{len(dlg_shots)}** · 允许无词：**{len(mute_shots)}** · 需补词：**{len(need_line)}**",
        f"- 校验 errors：{len(errors)} · warnings：{len(warnings)}",
        "",
        "## 开场 3 秒（名单自己翻面）",
        "",
        "异常物件：门房玻璃上的裁员名单。留下的问题：**名单最上怎么是她？**",
        "",
    ]
    for card in cards[:3]:
        grid = card.get("prompt_grid") or {}
        lines += [
            f"### {card['id']} · {card['duration']}s · from {card['from_old']}",
            "",
            f"- **one_action**：{card['one_action']}",
            f"- ① 主体＋单一动作：{grid.get('主体动作', '')}",
            f"- ② 镜头距离＋一个运镜：{grid.get('镜头运镜', '')}",
            f"- ③ 光线＋必要环境音：{grid.get('光线声音', '')}",
            f"- ④ 最终停在：{grid.get('停在', '')}",
            f"- **in_from**：{card['in_from']}",
            f"- **out_to**：{card['out_to']}",
            "",
        ]
    lines += [
        "## 总表",
        "",
        "| 新镜 | from_old | 场 | 秒 | 覆盖 | 景别 | one_action | 表情 | 对白 | dialogue_goes_to | 为何拆 |",
        "|---|---|---|---:|---|---|---|---|---|---|---|",
    ]
    for card in cards:
        lines.append(
            f"| {card['id']} | {card['from_old']} | {card['scene']} | {card['duration']} | "
            f"{card['coverage']} | {card['scale']} | {card['one_action'].replace('|', '／')} | "
            f"{card['expression'].replace('|', '／')} | {card['who'].replace('|', '／')} | "
            f"{card['dialogue_goes_to'].replace('|', '／')} | {card['why'].replace('|', '／')} |"
        )
    lines += ["", "## 逐镜卡片", ""]
    for card in cards:
        lines += [
            f"### {card['id']} · {card['scene']} · {card['duration']}s · from {card['from_old']}",
            "",
            f"- **one_action**：{card['one_action']}",
            f"- **still_start / 首帧 t=0**：{card['still_start']}",
            f"- **expression**：{card['expression']}",
            f"- **the_shot**：{card['the_shot']}",
            f"- **in_from**：{card['in_from']}",
            f"- **out_to**：{card['out_to']}",
            f"- **who**：{card['who']}",
            f"- **dialogue_goes_to**：{card['dialogue_goes_to']}",
            f"- **为何拆**：{card['why']}",
            "",
        ]
    if errors:
        lines += ["## 校验 errors", ""] + [f"- {e}" for e in errors] + [""]
    if warnings:
        lines += ["## 校验 warnings（节选）", ""] + [f"- {w}" for w in warnings[:40]] + [""]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def _write_review(cards, metrics, errors, warnings, long_takes, dlg_shots, rewrite_shots, mute_shots, need_line) -> None:
    by_old = {}
    for card in cards:
        by_old.setdefault(card["from_old"], []).append(card["id"])
    opening = cards[:3]
    lines = [
        "# EP01 重拆 v2 审核表",
        "",
        f"**给人批的。** 候选 **{metrics['shots']} 镜 / {metrics['total_sec']}s / ASL {metrics['asl']} / SPM {metrics['spm']}**。",
        "活表仍是 **29 镜锁画**（`.pipeline/shot_list.json`）。不要改 JSON、不要升活表、不要重出帧/片/SRT。",
        "",
        "- 候选源：`.pipeline/shot_list.ep01.resplit-v2.json`",
        "- 逐镜卡片：`03-storyboard/ep01-resplit-v2.md`",
        "",
        "## 页顶检查（先过这三行再批镜）",
        "",
        "| 检查 | 问句 | 本表怎么答 | 过？ |",
        "|---|---|---|---|",
        "| **开场·一动作** | 每个镜头是否只有一个主动作？ | SH001 纸边颤 / SH002 手停 / SH003 行自己翻面 | ☐ |",
        "| **开场·异常** | 3 秒内是否已经发生异常？ | 名单自己颤、手停、最上那行自己翻到她的名字 | ☐ |",
        "| **开场·问题** | 最后一帧是否留下明确问题？ | **名单最上怎么是她？** | ☐ |",
        "| **快** | 有没有闷镜？ | 默认 2–2.8s；>4s 只留给穿过/笔尖/对白时长 | ☐ |",
        "| **脸** | 每镜表情是否外放？ | 愣/横/怕/讥/咬牙/眼瞪大/嘴扯开，禁止若有所思 | ☐ |",
        "| **词** | 这镜信息是不是靠台词？ | 开场 3s 与透胸/穿过/笔尖无词；其余有 rewrite 映射或标需补词 | ☐ |",
        "",
        "## 开场 3 秒（四格）",
        "",
        "异常选了**门房玻璃上的裁员名单**（旧表已有物件，后面接得上 SH002 证据）。不要写纸箱。",
        "",
    ]
    for card in opening:
        grid = card.get("prompt_grid") or {}
        lines += [
            f"### {card['id']} · {card['duration']}s",
            "",
            f"可复制句式：近景，{card['one_action']}；{grid.get('镜头运镜', '')}；{grid.get('光线声音', '')}；最后停在{grid.get('停在', '')}。",
            "",
            "| 格 | 内容 |",
            "|---|---|",
            f"| ① 主体＋单一动作 | {grid.get('主体动作', '')} |",
            f"| ② 镜头距离＋一个运镜 | {grid.get('镜头运镜', '')} |",
            f"| ③ 光线＋必要环境音 | {grid.get('光线声音', '')} |",
            f"| ④ 最终停在哪个画面 | {grid.get('停在', '')} |",
            "",
        ]
    lines += [
        "## 怎么批",
        "",
        "| 字 | 意思 |",
        "|---|---|",
        "| **过** | 按此拆，进新表时就这样切 |",
        "| **改** | 留着这镜，但改秒、景别或 one_action |",
        "| **并** | 这两（或几）镜该是一镜 |",
        "",
        "写在最后一列。批完把本文件发回来，**不要自己改 JSON**。",
        "",
        "## 旧镜怎么被拆",
        "",
        "| 旧镜 | 新镜 |",
        "|---|---|",
    ]
    for i in range(1, 30):
        old_id = f"SH{i:03d}"
        news = by_old.get(old_id) or []
        mark = " ← 拆" if len(news) > 1 else ("（未用）" if not news else "（未拆）")
        lines.append(f"| {old_id} | {'、'.join(news) or '—'}{mark} |")

    groups = [
        ("EP01_SC01", "厂门·夹道", "factory-gate"),
        ("EP01_SC02", "杂物间", "storeroom"),
        ("EP01_SC03", "走廊·七线", "line-7"),
    ]
    for scene_id, title, loc in groups:
        group = [c for c in cards if c["scene"] == scene_id]
        sec = round(sum(float(c["duration"]) for c in group), 1)
        dull = [c["id"] for c in group if float(c["duration"]) >= 4 and not c["long"] and c["who"] == "—"]
        lines += [
            "",
            f"## {scene_id}　{title}",
            "",
            f"地点 `{loc}`。左右锁见活表 / 候选 JSON。",
            "",
            "| 新镜 | 旧镜 | 秒 | 景别/机位 | 画面上有谁 | one_action | 脸 | 这镜为什么拆 | 对白/独白归属 | 衔接（接/交） | 审核 |",
            "|---|---|---:|---|---|---|---|---|---|---|---|",
        ]
        for card in group:
            cam = f"{card['coverage']} / {card['scale']}" + (f" / {card['camera']}" if card["camera"] else "")
            lines.append(
                f"| {card['id']} | {card['from_old']} | {card['duration']} | {cam} | {card['names']} | "
                f"{card['one_action'].replace('|', '／')} | {card['expression'].replace('|', '／')} | "
                f"{card['why'].replace('|', '／')} | {card['dialogue_goes_to'].replace('|', '／')} | "
                f"接：{card['in_from']} / 交：{card['out_to']} | ☐ |"
            )
        extra = f"（{('、'.join(dull))}）" if dull else ""
        lines.append(f"**场节奏**：{len(group)} 镜 · {sec}s · 闷风险 {len(dull)}{extra}。")

    lines += [
        "",
        "## 词表统计",
        "",
        f"- writer `dialogue_ref`：{len(dlg_shots)} 镜",
        f"- rewrite 已映射：{len(rewrite_shots)} 镜",
        f"- 允许无词（开场/透胸/穿过/笔尖/冲击/对白后反应）：{len(mute_shots)} 镜",
        f"- **需补词**：{len(need_line)} 镜 — {('、'.join(c['id'] for c in need_line)) or '无'}",
        "",
        "## 长镜头（>4s）",
        "",
    ]
    if long_takes:
        for s in long_takes:
            lines.append(f"- {s['shot_id']} {s.get('duration_sec')}s · {s.get('long_take_reason')}")
    else:
        lines.append("- （无）")
    lines += [
        "",
        "## 批完怎么交",
        "",
        "1. 最后一列填 **过 / 改 / 并**。",
        "2. **不要改** `.pipeline/shot_list.ep01.resplit-v2.json`，更不要覆盖活表。",
        "3. 帧、视频、SRT 仍跟 29 镜锁画。",
        "",
    ]
    if errors:
        lines += ["## 机器校验 errors", ""] + [f"- {e}" for e in errors] + [""]
    OUT_REVIEW.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
